<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      DB::table('books')->insert([
        [
            'isbn' => '978-0-123456-47-2',
            'title' => 'The Great Gatsby',
            'cover' => '01J7RJEZAWFVXMX862YKPDGBHW.webp',
            'label' => 'Scribner',
            'edition' => '1st',
            'year' => '1925',
            'copies' => '10',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-0-765432-89-1',
            'title' => 'To Kill a Mockingbird',
            'cover' => '01J7RJHB8T2TWPCZQCEWWYYFW7.webp',
            'label' => 'J.B. Lippincott & Co.',
            'edition' => '1st',
            'year' => '1960',
            'copies' => '5',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-0-394523-22-6',
            'title' => '1984',
            'cover' => '01J7RJHYNT9FVMP58WT56T86Z3.webp',
            'label' => 'Secker & Warburg',
            'edition' => '1st',
            'year' => '1949',
            'copies' => '7',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-1-501102-79-3',
            'title' => 'The Catcher in the Rye',
            'cover' => '01J7RJJNHZADMHJ67R9W4YNENF.webp',
            'label' => 'Little, Brown and Company',
            'edition' => '2nd',
            'year' => '1951',
            'copies' => '6',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-0-671723-13-1',
            'title' => 'Moby Dick',
            'cover' => '01J7RJK7E3KZ24ZEAKH3RBE56D.webp',
            'label' => 'Harper & Brothers',
            'edition' => '1st',
            'year' => '1851',
            'copies' => '4',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-0-307742-90-9',
            'title' => 'Pride and Prejudice',
            'cover' => '01J7RJKWBNEH0C0K2ZZVNSRJK7.jpg',
            'label' => 'T. Egerton',
            'edition' => null,
            'year' => '1813',
            'copies' => '3',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-0-452284-22-3',
            'title' => 'The Hobbit',
            'cover' => '01J7RJP65453G666XGW6RQ508H.jpg',
            'label' => 'George Allen & Unwin',
            'edition' => '3rd',
            'year' => '1937',
            'copies' => '8',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-0-743273-58-4',
            'title' => 'Brave New World',
            'cover' => '01J7RJPRFMND35P391AMS7C3XN.jpg',
            'label' => 'Chatto & Windus',
            'edition' => null,
            'year' => '1932',
            'copies' => '6',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-0-000003-22-7',
            'title' => 'War and Peace',
            'cover' => '01J7RJQ7YAHH2RSDXDY8YZXYCF.webp',
            'label' => 'The Russian Messenger',
            'edition' => null,
            'year' => '1869',
            'copies' => '5',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-0-567898-77-1',
            'title' => 'The Alchemist',
            'cover' => '01J7RJQT3YHSC3ZKNEGR9M3Y22.jpg',
            'label' => 'HarperTorch',
            'edition' => null,
            'year' => '1988',
            'copies' => '9',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-0-198765-44-8',
            'title' => 'Fahrenheit 451',
            'cover' => '01J7RJRM1G0NNA411BCGV9FZGY.avif',
            'label' => 'Ballantine Books',
            'edition' => null,
            'year' => '1953',
            'copies' => '8',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-0-374280-19-8',
            'title' => 'The Kite Runner',
            'cover' => '01J7RJS4TSXVSM0XK8D6V1K0Q6.jpg',
            'label' => 'Riverhead Books',
            'edition' => null,
            'year' => '2003',
            'copies' => '4',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-0-394586-94-4',
            'title' => 'Slaughterhouse-Five',
            'cover' => '01J7RJSQSS7J19JWXT8HYNBW7T.jpg',
            'label' => 'Delacorte',
            'edition' => '1st',
            'year' => '1969',
            'copies' => '6',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-1-594201-52-3',
            'title' => 'Life of Pi',
            'cover' => '01J7RJTAE7140TETGWFW01FR9T.jpg',
            'label' => 'Houghton Mifflin Harcourt',
            'edition' => '1st',
            'year' => '2001',
            'copies' => '7',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'isbn' => '978-1-408838-74-5',
            'title' => 'The Road',
            'cover' => '01J7RJTYYVDEC0J0R6NKSK0V4Z.jpg',
            'label' => 'Alfred A. Knopf',
            'edition' => null,
            'year' => '2006',
            'copies' => '6',
            'volume' => null,
            'category_id' => Category::inRandomOrder()->first()->id,
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ]);
    }
}
